In [1]:
import numpy as np

Function that takes dimensions as tuples and returns a
Numpy array of the given dimension filled with the given value

In [2]:
def fun(a,b,c):
    d=np.full((a,b),c)
    return d
a=int(input())
b=int(input())
c=int(input()) 
print(fun(a,b,c))

3
3
5
[[5 5 5]
 [5 5 5]
 [5 5 5]]


Method that takes n Numpy arrays of same dimensions sums them and return the answer.

In [3]:
def math(a,b):
    sum1 = a+b
    return sum1


a=np.array([10,20,30])
b=np.array([40,50,60])
math(a,b)

array([50, 70, 90])

The method to return the top-left N X M sub matrix

In [4]:
def math1(a):
    return a[:2,:2]
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The top-left matrix is: \n",math1(a))

The top-left matrix is: 
 [[1 2]
 [4 5]]


The method to return the bottom-right N X M sub matrix

In [5]:
def math1(a):
    return a[1:,1:]
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The bottom-right matrix is: \n",math1(a))

The bottom-right matrix is: 
 [[5 6]
 [8 9]]


The method to return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's
standard deviation as values:

In [6]:
def math2(a):
    b= np.mean(a)
    c=np.std(a)
    dict1={"mean":b,"std":c}
    return dict1


a = np.array([1,2,3])
math2(a)

{'mean': 2.0, 'std': 0.816496580927726}